name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Hoặc branch bạn muốn deploy

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Docusaurus hoạt động ổn định hơn với Node.js 18

      - name: Install dependencies
        run: npm ci  # Cài đặt dependencies nhanh hơn, đáng tin cậy hơn

      - name: Build website
        env:
          GIT_USER: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build  # Chạy lệnh build website

      - name: Deploy website
        run: npm run deploy  # Chạy lệnh deploy lên GitHub Pages
